version: "3.9"

services:
  app:
    image: omersegal10/flask-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app_container
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Omer2002

  db:
    image: omersegal10/db-app:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: Omer2002
      MYSQL_DATABASE: Sports_db
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db-data:
