version: "3.8"

services:
  db:
    build:
      context: ./db
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: omer2002
      MYSQL_DATABASE: Sports_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  web:
    build:
      context: ./app
    container_name: flask_container
    environment:
      FLASK_ENV: development
      MYSQL_HOST: root
      MYSQL_USER: root
      MYSQL_PASSWORD: omer2002
      MYSQL_DB: Sports_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app

volumes:
  mysql_data:
