apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: defult
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: sports_project
      image: nginx:latest
      ports:
        - containerPort: 80
